echo $$
CUDA_VISIBLE_DEVICES=2,4 python3 fixed_main.py \
	--path-to-supernet /home/yixin/MLP-NAS/out/MLP-s16 \
	--model fixed-mixer \
	--dataset c10 \
	--img-size 224 \
	--batch-size 256 \
	--eval-batch-size 128 \
	--epochs 100 \
	--lr 1e-3 \
	--momentum 0.9 \
	--optimizer Adam \
	--scheduler cosine \
	--beta1 0.9 \
	--beta2 0.99 \
	--weight-decay 0.05 \
	--label-smoothing 0.1 \
	--warmup-epoch 10 \
	--clip-grad 0 \
	--cutmix-beta 0.5 \
	--cutmix-prob 0.5 \
	--distributed \
	--recovery-interval 0 \
	--use-timm-transform \
	--hflip 0.5 \
	--vflip 0. \
	--color-jitter 0.2 \
	--train-interpolation bilinear \
	--reprob 0.1 \
	--remode pixel \
	--recount 1 \
	--autoaugment v0r \
	--top-k 4 \
	--binarize-arch \
	--verbose
